language: node_js

node_js:
  - '6'

script: npm run cover

after_script:
  - cat ./tests/coverage/lcov.info | ./node_modules/.bin/coveralls

before_deploy: npm run compile
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    node: '6'
  email: adminlogin@ssense.com
  api_key:
    secure: Q4da+XgBnAErwkijL+oIA/dHPUtK6IHeG76axPxUZjexQbelV/MmydNwaqqoAXSa9qHbBbHZ1gZ+DSuaLeAqtdwZ2sTrF7/AeDMP+ww/YmAe58QKEnS6hvaeQJIMW4HZsvZgTDylziSSf3jSjybJnzYwl7RiGkVh+FI0iapL2HZF7QZyB43ytt77v60EeM3Uu5g66z8OBpW4+9du8bjRxTyF5Bs8shry4HO7uFY61549TNDG7UUze9W24Ms1ACRVygztGwb13Ws9rGadKKtgfgqWEu+Lu89r/MO6oaHD8s8rilBZ8xJKiH33oaflj7wrCMjSzpvnDHCCMMaif7nu3Xw/pNf20WCFhSVHPFUfwlNoTSiiX7jPnghWKc1Qf/0FS6AAzBC52pfcYTotL8RkOLeVomO/aO/iNdLLkMYQqpkDZN6FreNOlxAU+jN7Ru/N64vylzbSJtXvUo6pxMkgEoAPT39nLyH3hlEmG6HcKB8Q5F32bfd+1xreE9/5YIH5Fqb8ZL9pE2Y6FsLdGLG0FQuW8LwXkc5Vvw28aP/V2kT3GAxHg+K0twbpWQ3zwwP4qZIaDpIqGMcXHMYLropUmHfN5mZNhT/4i26769ZZp8nR/WgxZcwFHF/zkGxPgia2aeYW2QD8H8zllCDkR2WgLaQt7akPrwYoA+3OODZV8C8=
